<?php

/**
 * @file
 * Install and uninstall functions for force_crystal module.
 */

declare(strict_types=1);

/**
 * Implements hook_install().
 */
function force_crystal_install(): void {
  // Set default configuration values.
  $config = \Drupal::configFactory()->getEditable('force_crystal.settings');
  $config->set('text', 'Default content to be displayed if JS is disabled.')->save();

  \Drupal::service('router.builder')->rebuild();
}

/**
 * Implements hook_uninstall().
 */
function force_crystal_uninstall(): void {
  \Drupal::configFactory()->getEditable('force_crystal.settings')->delete();
}
