#!/usr/bin/env php
<?php

/**
 * @file
 * Stop development environment.
 */

declare(strict_types=1);

namespace DrupalExtensionScaffold\DevTools;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------
// Variables.
// -----------------------------------------------------------------------------

$webserver_port = resolve_webserver()['port'];

// -----------------------------------------------------------------------------

echo '===============================' . PHP_EOL;
echo '      💻 STOP ENVIRONMENT      ' . PHP_EOL;
echo '===============================' . PHP_EOL;
echo PHP_EOL;

// Custom scripts run while the server is still reachable.
run_custom_scripts('scripts', 'stop-');

TASK('Stopping previously started services on port %s, if any.', $webserver_port);
kill_port($webserver_port);
sleep(1);
PASS('Services stopped on port %s.', $webserver_port);

echo PHP_EOL;
echo '===============================' . PHP_EOL;
echo '   💻 ENVIRONMENT STOPPED ✅  ' . PHP_EOL;
echo '===============================' . PHP_EOL;
echo PHP_EOL;
