name: Draft release notes

on:
  push:
    tags:
      - '*'
    branches:
      - 1.x

permissions:
  contents: write

jobs:
  release-drafter:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Draft release notes
        uses: release-drafter/release-drafter@00ce30b0ce8a4d67bccfca59421cdf6c55dd0784 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
