name: Test

on:
  push:
    tags:
      - '**'
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: ${{ github.event_name == 'push' && 'npm' || '' }}

      - name: Install Node.js dependencies
        run: npm ci --ignore-scripts

      #;< DEV_CSPELL
      - name: Lint code with CSpell
        run: npm run lint-spell
        continue-on-error: ${{ vars.CI_CSPELL_IGNORE_FAILURE == '1' }}
      #;> DEV_CSPELL

      - name: Cache Composer dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.5
          extensions: gd, sqlite, pdo_sqlite

      - name: Assemble the codebase
        run: .devtools/assemble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #;< DEV_PHPCS
      - name: Lint code with PHPCS
        working-directory: build
        run: vendor/bin/phpcs
        continue-on-error: ${{ vars.CI_PHPCS_IGNORE_FAILURE == '1' }}
      #;> DEV_PHPCS

      #;< DEV_PHPSTAN
      - name: Lint code with PHPStan
        working-directory: build
        run: vendor/bin/phpstan
        continue-on-error: ${{ vars.CI_PHPSTAN_IGNORE_FAILURE == '1' }}
      #;> DEV_PHPSTAN

      #;< DEV_RECTOR
      - name: Lint code with Rector
        working-directory: build
        run: vendor/bin/rector --clear-cache --dry-run
        continue-on-error: ${{ vars.CI_RECTOR_IGNORE_FAILURE == '1' }}
      #;> DEV_RECTOR

      #;< DEV_TWIGCS
      - name: Lint code with Twig CS Fixer
        working-directory: build
        run: vendor/bin/twig-cs-fixer
        continue-on-error: ${{ vars.CI_TWIGCSFIXER_IGNORE_FAILURE == '1' }}
      #;> DEV_TWIGCS

      #;< DEV_NODEJS_LINT
      - name: Lint module code with NodeJS linters
        if: ${{ hashFiles('build/node_modules/.package-lock.json') != '' }}
        working-directory: build
        run: npm run lint
        continue-on-error: ${{ vars.CI_NODEJS_LINT_IGNORE_FAILURE == '1' }}
      #;> DEV_NODEJS_LINT

  test:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    strategy:
      fail-fast: false

      matrix:
        include:
          #;< DRUPAL_10
          - name: test-php-min-d10-stable
            php-version: 8.3
            drupal-version: 10

          - name: test-php-max-d10-stable
            php-version: 8.4
            drupal-version: 10

          #;> DRUPAL_10
          #;< DRUPAL_11
          - name: test-php-min-d11-stable
            php-version: 8.3
            drupal-version: 11

          - name: test-php-max-d11-stable
            php-version: 8.5
            drupal-version: 11

          - name: test-php-min-d11-legacy
            php-version: 8.3
            drupal-version: 11.1.0

          - name: test-php-max-d11-canary
            php-version: 8.5
            drupal-version: 11@beta
            stability: canary

          #;> DRUPAL_11
    #;< DEV_FUNCTIONAL_JAVASCRIPT
    services:
      chrome:
        image: selenium/standalone-chromium:latest@sha256:3400b92f1cddb2dfaaf358654e8f7d83d7be45192fb73c5f28c25faa28d36504
        ports:
          - 4444:4444
    #;> DEV_FUNCTIONAL_JAVASCRIPT

    name: ${{ matrix.name }}

    env:
      DRUPAL_VERSION: ${{ matrix.drupal-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Cache Composer dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Upgrade sqlite3
        run: |
          wget https://www.sqlite.org/2024/sqlite-autoconf-3450300.tar.gz -O /tmp/sqlite.tar.gz
          tar -xzf /tmp/sqlite.tar.gz -C /tmp
          cd /tmp/sqlite-autoconf-3450300
          ./configure CFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA=1" --prefix=/usr/local
          make && sudo make install
          sudo ldconfig

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd, sqlite, pdo_sqlite
          coverage: pcov

      # Disable Symfony deprecations helper for PHP 8.4+ until minor
      # versions of Drupal 10 and 11 fully support newer PHP versions.
      # @see https://www.drupal.org/project/drupal/issues/1267246
      - name: Update SYMFONY_DEPRECATIONS_HELPER for PHP 8.4+
        run: |
          if [ "$(php -r 'echo PHP_MAJOR_VERSION . PHP_MINOR_VERSION;')" -ge "84" ]; then
            echo "SYMFONY_DEPRECATIONS_HELPER=disabled" >> "$GITHUB_ENV"
          fi

      - name: Assemble the codebase
        run: .devtools/assemble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start built-in PHP server
        run: .devtools/start
        env:
          WEBSERVER_HOST: 0.0.0.0

      - name: Provision site
        run: .devtools/provision

      #;< DEV_JEST
      - name: Run JS tests
        if: ${{ hashFiles('build/node_modules/.package-lock.json') != '' }}
        working-directory: build
        run: npm test
        continue-on-error: ${{ vars.CI_NODEJS_TEST_IGNORE_FAILURE == '1' }}
      #;> DEV_JEST

      #;< DEV_PHPUNIT
      - name: Run tests
        working-directory: build
        run: php -d pcov.directory=.. vendor/bin/phpunit
        continue-on-error: ${{ vars.CI_TEST_IGNORE_FAILURE == '1' }}
        env:
          BROWSERTEST_OUTPUT_DIRECTORY: ../.logs/browser_output
          SIMPLETEST_DB: sqlite://tmp/db.sqlite

      - name: Upload test results as an artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: Artifacts (${{ matrix.name }})
          path: .logs/browser_output
          include-hidden-files: true

      - name: Upload coverage report as an artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{github.job}}-code-coverage-report-${{ matrix.name }}
          path: ./.logs/coverage
          include-hidden-files: true
          if-no-files-found: error

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: ${{ env.CODECOV_TOKEN != '' }}
        with:
          directory: ./.logs/coverage
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #;> DEV_PHPUNIT
